//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IgorTransExpressC
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        public int customerid { get; set; }
        public string name { get; set; }
        public string add1 { get; set; }
        public string add2 { get; set; }
        public string add3 { get; set; }
        public string county { get; set; }
        public string city { get; set; }
        public string postcode { get; set; }
        public string country { get; set; }
        public string telephone { get; set; }
        public string email { get; set; }
        public string account { get; set; }
    }
}
