//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IgorTransExpressC
{
    using System;
    using System.Collections.Generic;
    
    public partial class invdet
    {
        public int invdetid { get; set; }
        public int invoiceid { get; set; }
        public int line { get; set; }
        public System.DateTime delivery_date { get; set; }
        public string line_ref { get; set; }
        public string delivery_from { get; set; }
        public string delivery_to { get; set; }
        public string comments { get; set; }
        public decimal line_total { get; set; }
        public string @ref { get; set; }
    }
}
