//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IgorTransExpressC
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int userid { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public short access_level { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public string position { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
    }
}
